### ISSUE TITLE
command delObject (id exists or not) -> same result array

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.rest-api#27]
In the result of the command there is no notice that the id is really deleted.
There always is the same response body. 
Response Body:
```
{
  "results": []
}
```
Is it possible to get there an notice if the ObjectId was there and is then deleted, and if there was no object?
Which JSON options are possible?
![image](https://user-images.githubusercontent.com/84818934/174458802-2cf07c8c-dd91-4d73-b586-a8eea2fdd854.png)

**Comment by GermanBluefox** [comment]
In this case the command `delObject` just calls `adapter.delObject` function and it does not give error code if the object does not exist. BTW: `[DELETE] /objects`is now corrected
