### ISSUE TITLE
Unformated response for sendto-reguest

### ISSUE THREAD

**Issue by edyso** [ioBroker/ioBroker.rest-api#74]
It's possible to intergrate an option to get a raw-response(like plaintext for state) for the endpoint sendto? The callback-response is always json-formated or string-quoted:

```
let val="<html>hello</html>";
callback(val);

response: "<html>hello</html>"
```

=> no parsing in webbrowser, due to quotes.

My workaround is an implementation in php, web-call->some logic in php->calculated response in html.

PS: please edit the usage-example for sendto, the key/value for script in json-data is missing, I discovered it in the documantation of javascript-adapter/onmessage

**Comment by Apollon77** [comment]
This is a Restful API interface, so sorry the values should not be returned plain. Check simple-api adapter for things like that
